import type { Metadata } from "next"
import { Open_Sans } from "next/font/google"
import "./globals.css"
import React from "react"
import { WrappedLayout } from "./_layout"

const font = Open_Sans({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

const Layout = ({
    children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
    return (
        <html lang="en">
            <body
                className={`${font.className} antialiased`}
            >
                <WrappedLayout>
                    {children}
                </WrappedLayout>        
            </body>
        </html>
    )
}

export default Layout